services:
  - type: web
    name: health-monitor-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
